# <center><span style='color:red'>=== Zbiory miękkie ===
# 1. <span style='color:green'> Implementcja klasy do operowania na zbiorach miękkich
[*Klasyfiacja dla list, Klasyfikacja dla DataFrame, Obliczanie wartości obiektów do klasyfikacji*]

In [0]:
# importy
import pandas as pd
import random as rd

In [0]:
class SoftSet:
    @staticmethod
    def classify_list(x,y,test):
        #obliczenie składowych
        values = []
        for i in range(len(y)):
            score = 0
            for param in test.keys():
                score += y[i][param]*test[param]
            values.append(score)

        #znalezienie maksimum
        max_val = max(values)
        print(max_val)
        results = []
        for i in range(len(x)):
            if values[i] == max_val:
                results.append(x[i])

        #zwrócenie wyników
        return results

    @staticmethod
    def classify_dataframe(x,test):
        values = []
        for i in range(len(x.index)):
            score = 0
            for param in x.columns:
                score += x.iloc[i][param]*test[param]
            values.append(score)

        #znalezienie maksimum
        max_val = max(values)
        results = []
        for i in range(x.count()[0]):
            if values[i] == max_val:
                results.append(x.index[i])

        #zwrócenie wyników
        return results


    
    @staticmethod
    def calculate_values(x):
        # sepal.length, sepal.width, petal.length, petal.width, variety
        # _Setosa, _Virginica, _Versicolor
        iris_mean = x.mean()
        s_mean = x.where(x['variety'] == 'Setosa').mean()
        vi_mean = x.where(x['variety'] == 'Virginica').mean()
        ve_mean = x.where(x['variety'] == 'Versicolor').mean()
    

        s_values = {'sepal.length':int(s_mean[0]>iris_mean[0]),
                    'sepal.width':int(s_mean[1]>iris_mean[1]),
                    'petal.length':int(s_mean[2]>iris_mean[2]),
                    'petal.width':int(s_mean[3]>iris_mean[3])}

        vi_values = {'sepal.length':int(vi_mean[0]>iris_mean[0]),
                    'sepal.width':int(vi_mean[1]>iris_mean[1]),
                    'petal.length':int(vi_mean[2]>iris_mean[2]),
                    'petal.width':int(vi_mean[3]>iris_mean[3])}

        ve_values = {'sepal.length':int(ve_mean[0]>iris_mean[0]),
                    'sepal.width':int(ve_mean[1]>iris_mean[1]),
                    'petal.length':int(ve_mean[2]>iris_mean[2]),
                    'petal.width':int(ve_mean[3]>iris_mean[3])}



        result = pd.DataFrame(index=['Setosa','Virginica','Versicolor'],data=[s_values,vi_values,ve_values])

        return result

# 2. <span style="color:green"> Przykład użycia zbioru miękkiego dla warzyw:
[*Operowanie na listach*]

In [0]:
#stworzenie tablicy klas
Products = ['paprica','onion','carrot','salad','brocolli','sweet potatoe']
Attributes = [
    {'fresh':1,'frozen':0,'spicy':0,'sweet':1,'green':0,'red':1,'local':0,'tropical':1,'leafy':0,'tuberous':0},
    {'fresh':1,'frozen':0,'spicy':1,'sweet':0,'green':0,'red':1,'local':1,'tropical':0,'leafy':0,'tuberous':1},
    {'fresh':1,'frozen':0,'spicy':0,'sweet':1,'green':0,'red':0,'local':1,'tropical':0,'leafy':0,'tuberous':1},
    {'fresh':1,'frozen':0,'spicy':0,'sweet':0,'green':1,'red':0,'local':1,'tropical':0,'leafy':1,'tuberous':0},
    {'fresh':0,'frozen':1,'spicy':0,'sweet':0,'green':1,'red':0,'local':0,'tropical':1,'leafy':1,'tuberous':0},
    {'fresh':1,'frozen':0,'spicy':0,'sweet':1,'green':0,'red':0,'local':0,'tropical':1,'leafy':0,'tuberous':1}]

In [0]:
#próbka do klasyfikacji, np.: wymagania klienta
Client_A = {'fresh':1,'spicy':0.7,'red':1}
Client_B = {'frozen':1,'green':1,'sweet':1,'leafy':0.5}
Client_C = {'fresh':1,'green':0.7,'red':0.1,'sweet':1}
Clients = [Client_A, Client_B, Client_C]
for i in range(len(Clients)):
    print(SoftSet.classify_list(Products,Attributes, Clients[i]))

2.7
['onion']
2.5
['brocolli']
2.1
['paprica']

# 3. <span style="color:green"> Przykład użycia zbioru miękkiego dla irysów:
[*Operowanie na DataFrame*]

In [0]:
class DataProcessing:
    @staticmethod
    def shuffle(x):
        for i in range(len(x)-1,0,-1):
            j = rd.randint(0,i)
            x.iloc[i], x.iloc[j] = x.iloc[j], x.iloc[i]
        return x

    @staticmethod
    def split_set(x):
        k = int(len(x)*0.7)
        train = x[:k]
        val = x[k:]
        return train, val
    
    @staticmethod
    def normalize(x):
        val = x.select_dtypes(exclude="object")
        columns = val.columns.tolist()
        for c in columns:
            current_set = x.loc[:, c]
            maximum, minimum = max(current_set), min(current_set)
            for r in range(0,len(x),1):
                value = (x.at[r, c] - minimum) / (maximum - minimum)
                x.at[r, c] = value

In [0]:
iris = pd.read_csv('iris.csv')
iris.head(50)

,sepal.length,sepal.width,petal.length,petal.width,variety
0,5.1,3.5,1.4,0.2,Setosa
1,4.9,3.0,1.4,0.2,Setosa
2,4.7,3.2,1.3,0.2,Setosa
3,4.6,3.1,1.5,0.2,Setosa
4,5.0,3.6,1.4,0.2,Setosa
5,5.4,3.9,1.7,0.4,Setosa
6,4.6,3.4,1.4,0.3,Setosa
7,5.0,3.4,1.5,0.2,Setosa
8,4.4,2.9,1.4,0.2,Setosa
9,4.9,3.1,1.5,0.1,Setosa
10,5.4,3.7,1.5,0.2,Setosa
11,4.8,3.4,1.6,0.2,Setosa
12,4.8,3.0,1.4,0.1,Setosa
13,4.3,3.0,1.1,0.1,Setosa
14,5.8,4.0,1.2,0.2,Setosa
15,5.7,4.4,1.5,0.4,Setosa
16,5.4,3.9,1.3,0.4,Setosa
17,5.1,3.5,1.4,0.3,Setosa
18,5.7,3.8,1.7,0.3,Setosa
19,5.1,3.8,1.5,0.3,Setosa
20,5.4,3.4,1.7,0.2,Setosa
21,5.1,3.7,1.5,0.4,Setosa
22,4.6,3.6,1.0,0.2,Setosa
23,5.1,3.3,1.7,0.5,Setosa
24,4.8,3.4,1.9,0.2,Setosa
25,5.0,3.0,1.6,0.2,Setosa
26,5.0,3.4,1.6,0.4,Setosa
27,5.2,3.5,1.5,0.2,Setosa
28,5.2,3.4,1.4,0.2,Setosa
29,4.7,3.2,1.6,0.2,Setosa
30,4.8,3.1,1.6,0.2,Setosa
31,5.4,3.4,1.5,0.4,Setosa
32,5.2,4.1,1.5,0.1,Setosa
33,5.5,4.2,1.4,0.2,Setosa
34,4.9,3.1,1.5,0.2,Setosa
35,5.0,3.2,1.2,0.2,Setosa
36,5.5,3.5,1.3,0.2,Setosa
37,4.9,3.6,1.4,0.1,Setosa
38,4.4,3.0,1.3,0.2,Setosa
39,5.1,3.4,1.5,0.2,Setosa
40,5.0,3.5,1.3,0.3,Setosa
41,4.5,2.3,1.3,0.3,Setosa
42,4.4,3.2,1.3,0.2,Setosa
43,5.0,3.5,1.6,0.6,Setosa
44,5.1,3.8,1.9,0.4,Setosa
45,4.8,3.0,1.4,0.3,Setosa
46,5.1,3.8,1.6,0.2,Setosa
47,4.6,3.2,1.4,0.2,Setosa
48,5.3,3.7,1.5,0.2,Setosa
49,5.0,3.3,1.4,0.2,Setosa

In [0]:
DataProcessing.normalize(iris)
irisTrain, irisVal = DataProcessing.split_set(DataProcessing.shuffle(iris))

In [0]:
irisTrain = SoftSet.calculate_values(irisTrain)
irisVal = irisVal.reset_index()

correct = 0
for i in range(irisVal.count()[0]):
    print("========================= TEST",i,"=========================")
    guess = SoftSet.classify_dataframe(irisTrain,irisVal.iloc[i])
    anwser = [irisVal.iloc[i]['variety']]
    print('Guess:', guess,' | Anwser:', anwser)
    print()
    if guess == anwser:
        correct += 1

print("Accuracy:", correct/irisVal.count()[0])

========================= TEST 0 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Virginica']

========================= TEST 1 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Virginica']

========================= TEST 2 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Virginica']

========================= TEST 3 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Versicolor']

========================= TEST 4 =========================
Guess: ['Setosa']  | Anwser: ['Setosa']

========================= TEST 5 =========================
Guess: ['Setosa']  | Anwser: ['Setosa']

========================= TEST 6 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Versicolor']

========================= TEST 7 =========================
Guess: ['Setosa']  | Anwser: ['Setosa']

========================= TEST 8 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Setosa']

========================= TEST 9 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Versicolor']

========================= TEST 10 =========================
Guess: ['Setosa']  | Anwser: ['Setosa']

========================= TEST 11 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Versicolor']

========================= TEST 12 =========================
Guess: ['Setosa']  | Anwser: ['Setosa']

========================= TEST 13 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Versicolor']

========================= TEST 14 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Versicolor']

========================= TEST 15 =========================
Guess: ['Setosa']  | Anwser: ['Setosa']

========================= TEST 16 =========================
Guess: ['Setosa']  | Anwser: ['Setosa']

========================= TEST 17 =========================
Guess: ['Setosa']  | Anwser: ['Setosa']

========================= TEST 18 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Versicolor']

========================= TEST 19 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Virginica']

========================= TEST 20 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Versicolor']

========================= TEST 21 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Virginica']

========================= TEST 22 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Virginica']

========================= TEST 23 =========================
Guess: ['Setosa']  | Anwser: ['Setosa']

========================= TEST 24 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Virginica']

========================= TEST 25 =========================
Guess: ['Setosa']  | Anwser: ['Setosa']

========================= TEST 26 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Versicolor']

========================= TEST 27 =========================
Guess: ['Setosa']  | Anwser: ['Setosa']

========================= TEST 28 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Versicolor']

========================= TEST 29 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Versicolor']

========================= TEST 30 =========================
Guess: ['Setosa']  | Anwser: ['Setosa']

========================= TEST 31 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Virginica']

========================= TEST 32 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Versicolor']

========================= TEST 33 =========================
Guess: ['Setosa']  | Anwser: ['Setosa']

========================= TEST 34 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Virginica']

========================= TEST 35 =========================
Guess: ['Setosa']  | Anwser: ['Setosa']

========================= TEST 36 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Versicolor']

========================= TEST 37 =========================
Guess: ['Setosa']  | Anwser: ['Setosa']

========================= TEST 38 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Virginica']

========================= TEST 39 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Versicolor']

========================= TEST 40 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Virginica']

========================= TEST 41 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Virginica']

========================= TEST 42 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Virginica']

========================= TEST 43 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Versicolor']

========================= TEST 44 =========================
Guess: ['Virginica', 'Versicolor']  | Anwser: ['Virginica']

Accuracy: 0.3333333333333333